version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    volumes:
      - /var/app/node_modules
      - .:/var/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:3000"
    volumes:
      - /var/app/node_modules
      - .:/var/app
  
  aws:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "6000:3000"
    volumes:
      - /var/app/node_modules
      - .:/var/app
    command: ["npm","run","test"]